In [5]:
import os
import pandas as pd

os.chdir("C:\\Users\\juhic\\OneDrive\\Desktop\\03 UW Winter Course\\DATA 515 Software Design for Data Scientists\\01 Project")

## Reviews

In [2]:
reviews = pd.read_json("yelp_dataset~\\yelp_academic_dataset_review.json", lines = True)
reviews.drop(axis = 1, columns = ['date','funny','cool','useful'], inplace = True)

In [6]:
reviews.head()

,review_id,user_id,business_id,stars,text
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,"If you decide to eat here, just be aware it is..."
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,Family diner. Had the buffet. Eclectic assortm...
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo..."
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,Cute interior and owner (?) gave us tour of up...

## Business Dataset

In [8]:
business = pd.read_json("yelp_dataset~\\yelp_academic_dataset_business.json", lines = True)
business.drop(axis = 1, columns = ['hours','address'], inplace = True)
business.dropna(axis = 0, how = 'any', inplace = True)
str_cols = ['name','attributes','city','categories']
business[str_cols] = business[str_cols].apply(func = lambda x: x.str.strip().str.lower(), axis = 1)
restaurant = business.loc[business['categories'].str.contains('restaurant'),:].reset_index(drop = True)
restaurant.rename(columns = {'state':'code'}, inplace = True)
state_abb = pd.read_csv('State Abbreviations csvData.csv', usecols = ['State','Code'])
state_abb.rename(columns = {'State':'state', 'Code':'code'}, inplace = True)
restaurant = pd.merge(left = restaurant, right = state_abb, how = 'left', on = 'code')
restaurant.head(1)

,business_id,name,city,code,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,state
0,MTSW4McQd7CbVtyjqoe9mw,st honore pastries,philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,NaN,"restaurants, food, bubble tea, coffee & tea, b...",Pennsylvania

In [9]:
data = pd.merge(left = restaurant, right = reviews, how = 'inner', on = 'business_id')
data.head()

,business_id,name,city,code,postal_code,latitude,longitude,stars_x,review_count,is_open,attributes,categories,state,review_id,user_id,stars_y,text
0,MTSW4McQd7CbVtyjqoe9mw,st honore pastries,philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,NaN,"restaurants, food, bubble tea, coffee & tea, b...",Pennsylvania,BXQcBN0iAi1lAUxibGLFzA,6_SpY41LIHZuIaiDs5FMKA,4,This is nice little Chinese bakery in the hear...
1,MTSW4McQd7CbVtyjqoe9mw,st honore pastries,philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,NaN,"restaurants, food, bubble tea, coffee & tea, b...",Pennsylvania,uduvUCvi9w3T2bSGivCfXg,tCXElwhzekJEH6QJe3xs7Q,4,This is the bakery I usually go to in Chinatow...
2,MTSW4McQd7CbVtyjqoe9mw,st honore pastries,philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,NaN,"restaurants, food, bubble tea, coffee & tea, b...",Pennsylvania,a0vwPOqDXXZuJkbBW2356g,WqfKtI-aGMmvbA9pPUxNQQ,5,"A delightful find in Chinatown! Very clean, an..."
3,MTSW4McQd7CbVtyjqoe9mw,st honore pastries,philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,NaN,"restaurants, food, bubble tea, coffee & tea, b...",Pennsylvania,MKNp_CdR2k2202-c8GN5Dw,3-1va0IQfK-9tUMzfHWfTA,5,I ordered a graduation cake for my niece and i...
4,MTSW4McQd7CbVtyjqoe9mw,st honore pastries,philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,NaN,"restaurants, food, bubble tea, coffee & tea, b...",Pennsylvania,D1GisLDPe84Rrk_R4X2brQ,EouCKoDfzaVG0klEgdDvCQ,4,HK-STYLE MILK TEA: FOUR STARS\n\nNot quite su...

In [34]:
category = dict()
for c in data['categories']:
    for x in c.split(','):
        if x.strip() in category.keys():
            category[x.strip()] = category[x.strip()] + 1
        else:
            category[x.strip()] = 1
category

{'restaurants': 52268,
 'food': 15477,
 'bubble tea': 277,
 'coffee & tea': 4054,
 'bakeries': 1889,
 'burgers': 5636,
 'fast food': 6472,
 'sandwiches': 8366,
 'ice cream & frozen yogurt': 1088,
 'pubs': 1397,
 'italian': 4573,
 'bars': 8337,
 'american (traditional)': 8139,
 'nightlife': 8723,
 'greek': 779,
 'vietnamese': 852,
 'food trucks': 1008,
 'diners': 1494,
 'breakfast & brunch': 6239,
 'delis': 2393,
 'sushi bars': 1717,
 'japanese': 1830,
 'korean': 497,
 'cafes': 2756,
 'wine bars': 955,
 'steakhouses': 1506,
 'asian fusion': 1547,
 'hot dogs': 774,
 'seafood': 3539,
 'cocktail bars': 1405,
 'pizza': 7093,
 'chicken wings': 2966,
 'salad': 3064,
 'soup': 1061,
 'eatertainment': 17,
 'arts & entertainment': 1086,
 'brewpubs': 118,
 'breweries': 407,
 'specialty food': 2015,
 'pasta shops': 187,
 'chinese': 3169,
 'event planning & services': 3070,
 'caterers': 2059,
 'pets': 33,
 'pet adoption': 12,
 'american (new)': 6097,
 'sports bars': 1797,
 'gastropubs': 513,
 'beer bar': 640,
 'lounges': 695,
 'wraps': 310,
 'automotive': 288,
 'gas stations': 257,
 'convenience stores': 535,
 'venues & event spaces': 783,
 'juice bars & smoothies': 1015,
 'fruits & veggies': 127,
 'sporting goods': 23,
 'sports wear': 5,
 'fashion': 60,
 'shopping': 620,
 'cajun/creole': 923,
 'mexican': 4600,
 'french': 503,
 'moroccan': 49,
 'mediterranean': 1263,
 'live/raw food': 88,
 'beer': 1156,
 'wine & spirits': 1156,
 'filipino': 108,
 'barbeque': 1694,
 'performing arts': 42,
 'hotels & travel': 421,
 'beauty & spas': 86,
 'museums': 18,
 'hotels': 287,
 'cinema': 27,
 'resorts': 29,
 'day spas': 28,
 'chicken shop': 808,
 'thai': 971,
 'bagels': 600,
 'jazz & blues': 108,
 'southern': 988,
 'hawaiian': 185,
 'street vendors': 261,
 'irish': 215,
 'music venues': 512,
 'tobacco shops': 29,
 'hookah bars': 134,
 'vegan': 856,
 'soul food': 539,
 'tapas/small plates': 440,
 'shanghainese': 17,
 'szechuan': 114,
 'karaoke': 188,
 'irish pub': 123,
 'coffee roasteries': 140,
 'cupcakes': 97,
 'caribbean': 590,
 'trinidadian': 17,
 'tex-mex': 919,
 'party & event planning': 185,
 'ethnic food': 515,
 'gluten-free': 777,
 'latin american': 810,
 'comfort food': 746,
 'donuts': 475,
 'acai bowls': 176,
 'organic stores': 71,
 'vegetarian': 1158,
 'pakistani': 228,
 'indian': 838,
 'food delivery services': 863,
 'halal': 362,
 'food stands': 423,
 'seafood markets': 218,
 'active life': 327,
 'bowling': 51,
 'buffets': 622,
 'local flavor': 451,
 'empanadas': 56,
 'desserts': 1838,
 'middle eastern': 588,
 'tacos': 1020,
 'puerto rican': 99,
 'festivals': 35,
 'whiskey bars': 55,
 'honduran': 24,
 'ramen': 223,
 'noodles': 382,
 'spanish': 286,
 'cheesesteaks': 614,
 'african': 115,
 'kebab': 90,
 'turkish': 85,
 'social clubs': 36,
 'arcades': 119,
 'race tracks': 3,
 'mini golf': 8,
 'go karts': 2,
 'tea rooms': 102,
 'lebanese': 83,
 'grocery': 831,
 'imported food': 118,
 'creperies': 165,
 'gelato': 91,
 'golf': 86,
 'poke': 187,
 'shaved ice': 73,
 'dance clubs': 142,
 'falafel': 103,
 'pretzels': 100,
 'internet cafes': 84,
 'wineries': 82,
 'tapas bars': 226,
 'fish & chips': 202,
 'dive bars': 282,
 'pool halls': 68,
 'peruvian': 82,
 'art galleries': 46,
 'canadian (new)': 261,
 'beer gardens': 109,
 'ukrainian': 18,
 'malaysian': 30,
 'burmese': 18,
 'cuban': 283,
 'health markets': 176,
 'personal chefs': 44,
 'do-it-yourself food': 61,
 'sicilian': 16,
 'farmers market': 122,
 'themed cafes': 28,
 "women's clothing": 11,
 'pet sitting': 3,
 'accessories': 7,
 'pet stores': 11,
 'pet services': 11,
 'vitamins & supplements': 18,
 'meat shops': 229,
 'party equipment rentals': 8,
 'sardinian': 4,
 'laotian': 48,
 'teppanyaki': 38,
 'dominican': 44,
 'ethiopian': 67,
 'food court': 130,
 'shopping centers': 56,
 'it services & computer repair': 4,
 'local services': 79,
 'souvenir shops': 9,
 'wine tasting room': 29,
 'persian/iranian': 40,
 'hong kong style cafe': 6,
 'taiwanese': 77,
 'modern european': 131,
 'pan asian': 69,
 'casinos': 57,
 'new mexican cuisine': 111,
 'wine tasting classes': 8,
 'education': 55,
 'tasting classes': 10,
 'oriental': 3,
 'florists': 53,
 'flowers & gifts': 100,
 'funeral services & cemeteries': 1,
 'comedy clubs': 24,
 'outdoor gear': 3,
 'bed & breakfast': 64,
 'german': 125,
 'boat charters': 11,
 'professional services': 59,
 'business consulting': 3,
 'veterinarians': 2,
 'cheese shops': 86,
 'christmas trees': 2,
 'home & garden': 68,
 'arabic': 36,
 'tiki bars': 48,
 'argentine': 34,
 'fitness & instruction': 39,
 'yoga': 14,
 'portuguese': 33,
 'dim sum': 140,
 'hot pot': 75,
 'home services': 69,
 'real estate': 25,
 'kitchen incubators': 2,
 'butcher': 86,
 'car stereo installation': 1,
 'auto detailing': 4,
 'trailer repair': 1,
 'parking': 4,
 'self storage': 4,
 'rv repair': 1,
 'smog check stations': 1,
 'auto repair': 7,
 'oil change stations': 2,
 'counseling & mental health': 3,
 'transmission repair': 1,
 'health & medical': 71,
 'body shops': 4,
 'windshield installation & repair': 1,
 'auto glass services': 3,
 'tires': 4,
 'roadside assistance': 1,
 'battery stores': 1,
 'tennis': 15,
 'home cleaning': 4,
 'thrift stores': 4,
 'fondue': 27,
 'indoor playcentre': 35,
 'kids activities': 42,
 'poutineries': 26,
 'kosher': 73,
 'religious organizations': 22,
 'custom cakes': 74,
 'skin care': 12,
 'hair salons': 18,
 'donairs': 76,
 'party supplies': 9,
 'cantonese': 93,
 'international grocery': 102,
 'candy stores': 41,
 'brasseries': 47,
 'distilleries': 20,
 'community service/non-profit': 22,
 'used bookstore': 4,
 'salvadoran': 60,
 'golf equipment': 4,
 'chiropractors': 3,
 'mongolian': 36,
 'country clubs': 40,
 'british': 75,
 'patisserie/cake shop': 56,
 'waffles': 190,
 'home decor': 19,
 'wedding planning': 54,
 'syrian': 9,
 'musicians': 7,
 'boating': 17,
 'gay bars': 43,
 'herbs & spices': 16,
 'pop-up restaurants': 75,
 'armenian': 15,
 'chocolatiers & shops': 54,
 'churches': 8,
 'international': 7,
 'drugstores': 63,
 'venezuelan': 48,
 'wholesalers': 29,
 'specialty schools': 24,
 'cooking classes': 32,
 'arts & crafts': 49,
 'cooking schools': 19,
 'food tours': 14,
 'yelp events': 16,
 'tours': 49,
 'educational services': 4,
 'financial services': 11,
 'banks & credit unions': 6,
 'colombian': 67,
 'brazilian': 77,
 'haitian': 20,
 'couriers & delivery services': 5,
 'russian': 42,
 'czech': 6,
 'himalayan/nepalese': 21,
 'delicatessen': 22,
 'parks': 15,
 'dog parks': 4,
 'beer tours': 5,
 'adult entertainment': 33,
 'club crawl': 2,
 'electronics repair': 1,
 'smokehouse': 66,
 'polish': 43,
 'hainan': 1,
 'books': 34,
 'mags': 34,
 'music & video': 34,
 'bookstores': 20,
 'sports clubs': 12,
 'beaches': 14,
 'swimming pools': 15,
 'photography stores & services': 8,
 'afghan': 44,
 'gun/rifle ranges': 3,
 'cabaret': 8,
 'cafeteria': 47,
 'barbers': 8,
 'cambodian': 18,
 'bartenders': 13,
 'motorcycle dealers': 3,
 'tuscan': 7,
 'restaurant supplies': 25,
 'public markets': 11,
 'jewelry': 9,
 'somali': 2,
 'building supplies': 5,
 'herbal shops': 5,
 'movers': 6,
 'hardware stores': 2,
 'junk removal & hauling': 3,
 'amusement parks': 21,
 'indonesian': 23,
 'public services & government': 33,
 'departments of motor vehicles': 8,
 'wholesale stores': 26,
 'cosmetics & beauty supply': 13,
 'nutritionists': 19,
 'batting cages': 2,
 'piano bars': 33,
 'senegalese': 6,
 'appliances & repair': 3,
 'crane services': 1,
 'heating & air conditioning/hvac': 5,
 'cards & stationery': 4,
 'shared office spaces': 11,
 'coffeeshops': 2,
 "children's clothing": 4,
 'department stores': 23,
 "men's clothing": 7,
 'grilling equipment': 2,
 'beverage store': 34,
 'strip clubs': 4,
 'macarons': 18,
 'golf lessons': 10,
 'massage': 17,
 'car dealers': 5,
 'bar crawl': 10,
 'singaporean': 9,
 'boat tours': 3,
 'fireworks': 1,
 'cosmetic surgeons': 2,
 'doctors': 10,
 'nail salons': 9,
 'guns & ammo': 1,
 'pediatricians': 2,
 'waxing': 3,
 'hair removal': 4,
 'pool & billiards': 5,
 'bistros': 33,
 'cannabis dispensaries': 4,
 'leisure centers': 5,
 'laser tag': 6,
 'maternity wear': 1,
 'travel services': 11,
 'austrian': 5,
 'shaved snow': 7,
 'child care & day care': 2,
 'parent cafes': 1,
 'basque': 39,
 'eyewear & opticians': 1,
 'personal shopping': 9,
 'pop-up shops': 10,
 'kombucha': 19,
 'calabrian': 1,
 'iberian': 10,
 'australian': 13,
 'stadiums & arenas': 3,
 'kids hair salons': 1,
 'wine tours': 6,
 'farms': 7,
 'historical tours': 7,
 'japanese curry': 13,
 'home theatre installation': 1,
 'tv mounting': 1,
 'massage therapy': 9,
 'naturopathic/holistic': 3,
 'vape shops': 8,
 'cannabis clinics': 5,
 'drive-thru bars': 3,
 'playgrounds': 6,
 'ethnic grocery': 22,
 'car wash': 3,
 'country dance halls': 3,
 'musical instruments & teachers': 1,
 'south african': 6,
 'preschools': 3,
 'elementary schools': 2,
 'pawn shops': 1,
 'popcorn shops': 7,
 'dinner theater': 35,
 'walking tours': 4,
 'izakaya': 16,
 'nicaraguan': 6,
 'traditional chinese medicine': 4,
 'party bus rentals': 3,
 'bus tours': 2,
 'bangladeshi': 14,
 'religious items': 1,
 'mobile phone repair': 2,
 'pharmacy': 9,
 'lawn services': 2,
 'landscaping': 3,
 'food banks': 2,
 'kitchen & bath': 22,
 'ski resorts': 2,
 'antiques': 8,
 'horseback riding': 2,
 'scottish': 5,
 'print media': 3,
 'mass media': 5,
 'pancakes': 14,
 'unofficial yelp events': 2,
 'fishing': 5,
 'dance schools': 1,
 'eyebrow services': 2,
 'psychiatrists': 1,
 'neurologist': 1,
 'medical spas': 5,
 'family practice': 1,
 'appliances': 11,
 'furniture stores': 14,
 'wigs': 6,
 'belgian': 24,
 'hobby shops': 11,
 'nurseries & gardening': 12,
 'gyms': 11,
 'recreation centers': 10,
 'trainers': 4,
 'visitor centers': 2,
 'soccer': 2,
 'amateur sports teams': 4,
 'tax services': 1,
 'lahmacun': 1,
 'gift shops': 34,
 'landmarks & historical buildings': 16,
 'music & dvds': 3,
 'toy stores': 2,
 'dietitians': 4,
 'floral designers': 1,
 'animal shelters': 1,
 'discount store': 5,
 'outlet stores': 6,
 'guest houses': 3,
 'egyptian': 16,
 'sri lankan': 3,
 'tattoo': 3,
 'gymnastics': 1,
 'pilates': 1,
 'medical centers': 2,
 'taxis': 2,
 'public transportation': 2,
 'airport shuttles': 2,
 'transportation': 9,
 'train stations': 1,
 'uzbek': 8,
 'skating rinks': 6,
 'mattresses': 3,
 'scandinavian': 11,
 'interior design': 4,
 'cigar bars': 10,
 'adult education': 3,
 'buddhist temples': 3,
 'tabletop games': 12,
 'electronics': 4,
 'mobile phones': 2,
 'paint & sip': 2,
 'lan centers': 3,
 'trampoline parks': 2,
 'used car dealers': 1,
 'rafting/kayaking': 3,
 'bike rentals': 6,
 'paddleboarding': 2,
 'champagne bars': 15,
 'flea markets': 2,
 'videos & video game rental': 4,
 'auto customization': 2,
 'aquariums': 3,
 'bikes': 4,
 'bike repair/maintenance': 4,
 'watches': 1,
 'home organization': 2,
 'israeli': 2,
 'coffee & tea supplies': 2,
 'newspapers & magazines': 5,
 'leather goods': 1,
 'supper clubs': 3,
 'real estate services': 1,
 'used': 2,
 'vintage & consignment': 2,
 'property management': 3,
 'cideries': 6,
 'speakeasies': 13,
 'beer hall': 1,
 'olive oil': 3,
 'dry cleaning & laundry': 3,
 'kitchen supplies': 3,
 'wheel & rim repair': 1,
 'internal medicine': 1,
 'comic books': 1,
 'private tutors': 1,
 'tutoring centers': 2,
 'georgian': 4,
 'video game stores': 1,
 'djs': 1,
 'marketing': 1,
 'graphic design': 2,
 'advertising': 2,
 'jails & prisons': 1,
 'pest control': 3,
 'accountants': 2,
 'financial advising': 1,
 'plumbing': 5,
 'water heater installation/repair': 2,
 'contractors': 7,
 'clothing rental': 1,
 'airports': 5,
 'fuzhou': 1,
 'grill services': 1,
 'tree services': 4,
 'holiday decorations': 1,
 'real estate agents': 2,
 'officiants': 1,
 'apartments': 4,
 'hostels': 3,
 'shoe stores': 2,
 'lawyers': 3,
 'billing services': 1,
 'plastic surgeons': 1,
 'golf cart rentals': 1,
 'honey': 2,
 'wildlife control': 1,
 'osteopaths': 1,
 'hospitals': 3,
 'propane': 2,
 'costumes': 1,
 'hunting & fishing supplies': 4,
 'auto parts & supplies': 2,
 'boat repair': 1,
 'marinas': 2,
 'tableware': 2,
 'roofing': 1,
 'solar installation': 1,
 'head shops': 2,
 'community centers': 1,
 'cultural center': 5,
 'rolfing': 1,
 'check cashing/pay-day loans': 1,
 'kiosk': 1,
 'adult': 4,
 'colleges & universities': 5,
 'art museums': 4,
 'roman': 1,
 'ticket sales': 3,
 'axe throwing': 4,
 'painters': 2,
 'pressure washers': 1,
 'water purification services': 1,
 'septic services': 2,
 'beach bars': 1,
 'horse racing': 1,
 'piercing': 2,
 'pet training': 1,
 'vacation rentals': 1,
 'vinyl records': 4,
 'blow dry/out services': 1,
 'hair extensions': 1,
 'hair stylists': 2,
 'hungarian': 6,
 'dance studios': 1,
 'shipping centers': 1,
 'spiritual shop': 2,
 'hakka': 2,
 'photographers': 4,
 'homeowner association': 1,
 'team building activities': 4,
 'bocce ball': 2,
 'candle stores': 1,
 'art classes': 3,
 'eyelash service': 1,
 'guamanian': 1,
 'climbing': 1,
 'perfume': 2,
 'laundry services': 2,
 'zoos': 1,
 'pet photography': 1,
 'csa': 4,
 'recycling center': 1,
 'web design': 2,
 'airport lounges': 5,
 'pet groomers': 2,
 'limos': 1,
 'tonkatsu': 1,
 'donburi': 1,
 'travel agents': 1,
 'supernatural readings': 4,
 'acupuncture': 2,
 'weight loss centers': 3,
 'audio/visual equipment rental': 1,
 'escape games': 2,
 'rv parks': 1,
 'pita': 1,
 'dry cleaning': 1,
 'laundromat': 1,
 'hiking': 3,
 'dentists': 2,
 'general dentistry': 1,
 'outdoor furniture stores': 2,
 'reiki': 1,
 'botanical gardens': 2,
 'drive-in theater': 1,
 'municipality': 1,
 'eastern european': 2,
 'party characters': 1,
 'threading services': 1,
 'session photography': 1,
 'auction houses': 1,
 'music production services': 1,
 'recording & rehearsal studios': 2,
 'packing services': 1,
 'car share services': 1,
 'office cleaning': 2,
 'brewing supplies': 3,
 'ice delivery': 1,
 'internet service providers': 1,
 'university housing': 1,
 'truck rental': 1,
 'commercial truck dealers': 1,
 'customized merchandise': 1,
 'screen printing/t-shirt printing': 1,
 'service stations': 1,
 'pet boarding': 1,
 "men's hair salons": 1,
 'fireplace services': 3,
 'virtual reality centers': 2,
 'pick your own farms': 1,
 'art tours': 1,
 'livestock feed & supply': 1,
 'oral surgeons': 1,
 'skate shops': 1,
 'diagnostic imaging': 1,
 'diagnostic services': 1,
 'radiologists': 1,
 'sports betting': 2,
 'bridal': 1,
 'airport terminals': 2,
 'dumplings': 2,
 'flight instruction': 1,
 'cucina campana': 1,
 'carpet cleaning': 2,
 'nail technicians': 1,
 'radio stations': 1,
 'fire departments': 1,
 'cabinetry': 1,
 'countertop installation': 2,
 'tiling': 1,
 'ethical grocery': 1,
 'trains': 1,
 'personal injury law': 1,
 'business law': 1,
 'contract law': 1,
 'real estate law': 1,
 'employment law': 1,
 'legal services': 1,
 'divorce & family law': 1,
 'general litigation': 1,
 'personal assistants': 1,
 'trivia hosts': 1,
 'conveyor belt sushi': 1,
 'rest stops': 2,
 'landscape architects': 2,
 'reflexology': 3,
 'libraries': 2,
 'wedding chapels': 1,
 'water stores': 1,
 'special education': 1,
 'hotel bar': 1,
 'makeup artists': 1,
 'health retreats': 1,
 'airlines': 1,
 'hindu temples': 1,
 'investing': 1,
 'auto loan providers': 1,
 'haunted houses': 1,
 'furniture reupholstery': 2,
 'damage restoration': 2,
 'air duct cleaning': 1,
 'commercial truck repair': 1,
 'security systems': 1,
 'gardeners': 1,
 'irrigation': 1,
 'garage door services': 1,
 'keys & locksmiths': 1,
 'serbo croatian': 1,
 'towing': 1,
 'hair loss centers': 1,
 'gemstones & minerals': 1}

In [35]:
state = dict()
for s in data['state']:
    if s in state.keys():
        state[s] = state[s] + 1
    else:
        state[s] = 1
state

{'Pennsylvania': 12644,
 'Tennessee': 4353,
 'Missouri': 4248,
 'Florida': 8732,
 'Indiana': 4150,
 nan: 2411,
 'Nevada': 1675,
 'Illinois': 983,
 'Arizona': 2675,
 'Louisiana': 3641,
 'New Jersey': 3343,
 'California': 1161,
 'Delaware': 962,
 'Idaho': 1304,
 'North Carolina': 1,
 'Colorado': 1,
 'Hawaii': 1,
 'Montana': 1}

In [37]:
city = dict()
for c in data['city']:
    if c in city.keys():
        city[c] = city[c] + 1
    else:
        city[c] = 1
city

{'philadelphia': 5857,
 'ashland city': 24,
 'affton': 18,
 'nashville': 2506,
 'tampa bay': 36,
 'indianapolis': 2863,
 'largo': 312,
 'edmonton': 2168,
 'reno': 1290,
 'white house': 47,
 'ardmore': 126,
 'exton': 140,
 'alton': 84,
 'tucson': 2473,
 'bala cynwyd': 54,
 'tampa': 2968,
 'harvey': 117,
 'west chester': 281,
 'williamstown': 46,
 'glenolden': 28,
 'wesley chapel': 159,
 'burlington': 86,
 'santa barbara': 767,
 'new orleans': 2262,
 'camden': 59,
 'saint louis': 1791,
 'fairview heights': 77,
 'wilmington': 622,
 'treasure island': 36,
 'brentwood': 187,
 'woodbury': 50,
 'sparks': 334,
 'madison': 96,
 'ewing': 59,
 'riverview': 199,
 'saint petersburg': 491,
 'warrington': 60,
 'st. louis': 544,
 'lutz': 178,
 'langhorne': 100,
 'king of prussia': 191,
 'carmel': 291,
 'clearwater': 679,
 'new port richey': 227,
 'avon': 110,
 'normandy': 4,
 'franklin': 444,
 'meridian': 313,
 'st albert': 45,
 'hermitage': 97,
 'downingtown': 97,
 'sherwood park': 136,
 'virginia city': 10,
 'trenton': 193,
 'bensalem': 165,
 'marana': 39,
 'brandon': 327,
 'odessa': 41,
 'horsham': 61,
 'brownsburg': 79,
 'malvern': 113,
 'maple shade': 49,
 'lansdale': 133,
 'ballwin': 72,
 'cedarbrook': 1,
 'goodlettsville': 76,
 'narberth': 34,
 'oldsmar': 87,
 'isla vista': 55,
 'glassboro': 73,
 'haddonfield': 63,
 'kenner': 228,
 'montgomeryville': 19,
 'chesterfield': 67,
 'spring hill': 153,
 'pennsville': 26,
 'haddon heights': 25,
 'goleta': 220,
 'hazelwood': 43,
 'view': 1,
 'edwardsville': 128,
 'brookhaven': 30,
 'noblesville': 10,
 'metairie': 522,
 'new hope': 100,
 'norristown': 162,
 'cherry hill': 297,
 'st louis': 150,
 'st petersburg': 121,
 'boise': 850,
 'mount juliet': 103,
 'fishers': 203,
 'palmyra': 15,
 'media': 141,
 'saint charles': 122,
 'high ridge': 24,
 'conshohocken': 103,
 'hernando beach': 12,
 'florissant': 165,
 'newtown': 101,
 'chadds ford': 41,
 'woodstown': 10,
 'plant city': 111,
 'levittown': 117,
 'ruskin': 52,
 'town and country': 12,
 'lebanon': 27,
 'bryn mawr': 93,
 'jennings': 7,
 'pottstown': 138,
 'carpinteria': 81,
 'voorhees': 83,
 'spring city': 21,
 'southampton': 60,
 'riverside': 13,
 'lambertville': 57,
 'ambler': 83,
 'madeira beach': 66,
 'godfrey': 16,
 'florence township': 4,
 'mascoutah': 9,
 'marlton': 123,
 'delran': 39,
 'huntingdon valley': 47,
 'collingswood': 71,
 'creve coeur': 71,
 'fort washington': 15,
 'wayne': 128,
 'limerick': 17,
 'turnersville': 34,
 'holiday': 38,
 'doylestown': 156,
 'port richey': 106,
 'westwego': 28,
 'sicklerville': 83,
 'bridgeport': 19,
 'moorestown': 68,
 'mount laurel township': 5,
 'glen carbon': 18,
 'washington crossing': 7,
 'zionsville': 73,
 'st charles': 42,
 'drexel hill': 67,
 'verdi': 16,
 'dunedin': 188,
 'seminole': 120,
 'folsom': 48,
 'fenton': 89,
 'eagle': 92,
 'university city': 60,
 'arnold': 95,
 'collegeville': 78,
 'springfield': 126,
 'kimberton': 3,
 'east norriton': 34,
 'harleysville': 40,
 'jenkintown': 68,
 'granite city': 50,
 'dublin': 11,
 'harahan': 56,
 'old hickory': 33,
 'palm harbor': 208,
 'phoenixville': 140,
 'temple terr': 2,
 'pitman': 30,
 'mullica hill': 18,
 'ferguson': 24,
 'smyrna': 167,
 'fairless hills': 36,
 'newtown square': 59,
 'des peres': 50,
 'paoli': 51,
 'st. petersburg': 405,
 'trooper': 8,
 'earth city': 5,
 'mount laurel': 110,
 'woodlyn': 17,
 'lumberton': 19,
 'lahaska': 17,
 'pinellas park': 169,
 'woolwich twp': 1,
 'belleville': 146,
 'bridgeton': 72,
 'waterloo': 32,
 'voorhees township': 31,
 'sun city center': 17,
 'willow grove': 92,
 'belle chasse': 21,
 'glenside': 59,
 'north wales': 97,
 'yardley': 52,
 'brooklawn': 12,
 'gulfport': 55,
 'west berlin': 25,
 'darby': 11,
 'morrisville': 48,
 'gallatin': 63,
 'rosemont': 6,
 'broomall': 44,
 'la vergne': 47,
 'barrington': 16,
 'cahokia': 13,
 'greenbrier': 12,
 'chalfont': 41,
 'whiteland': 8,
 'sewell': 86,
 'antioch': 103,
 'swedesboro': 33,
 'royersford': 74,
 'eddystone': 8,
 'east greenville': 1,
 'st pete beach': 44,
 'maplewood': 52,
 'apollo beach': 42,
 'freeburg': 5,
 "land o' lakes": 31,
 'ewing township': 26,
 'clearwater beach': 77,
 'glen mills': 76,
 'audubon': 52,
 'bellmawr': 20,
 'aston': 51,
 'woodbury heights': 10,
 'prospect park': 28,
 'willingboro township': 3,
 'abington': 54,
 'morton': 15,
 'beaumont': 8,
 'st. pete beach': 69,
 'hudson': 96,
 'swansea': 22,
 'tarpon springs': 152,
 'blue bell': 66,
 'plainfield': 104,
 'lansdowne': 43,
 'seffner': 45,
 'valrico': 77,
 'glenmoore': 4,
 'collinsville': 71,
 'oaks': 15,
 'quakertown': 30,
 'mount ephraim': 12,
 'greenwood': 207,
 'atco': 9,
 'warminster': 93,
 'blackwood': 47,
 'speedway': 27,
 'ridley park': 21,
 'medford': 72,
 'newark': 146,
 'penns grove': 11,
 'gilbertsville': 23,
 'mt. juliet': 29,
 'land o lakes': 20,
 'essington': 14,
 'arabi': 15,
 'eagleville': 12,
 'mendenhall': 4,
 'maryland heights': 88,
 'maryville': 17,
 'new castle': 102,
 'schwenksville': 22,
 'saint pete beach': 26,
 'claymont': 23,
 'havertown': 91,
 'columbia': 30,
 'chester': 28,
 'upper darby': 104,
 'shiloh': 14,
 'zephyrhills': 60,
 'gibbsboro': 6,
 'gretna': 137,
 'bellevue': 11,
 'secane': 5,
 'hendersonville': 183,
 'bristol': 48,
 'terrytown': 31,
 'st.ann': 1,
 'elverson': 1,
 'clementon': 43,
 'greenville': 7,
 'bordentown': 40,
 'hatboro': 63,
 'riverton': 6,
 'willingboro': 31,
 'dover': 7,
 'troy': 27,
 'kennett square': 88,
 'spring house': 14,
 'merchantville': 26,
 'manchester': 25,
 'o fallon': 26,
 'spanish springs': 10,
 'chalmette': 64,
 'wimauma': 6,
 'mooresville': 39,
 'mt juliet': 15,
 'trappe': 9,
 'green valley': 26,
 'shamong': 5,
 'kirkwood': 82,
 'jefferson': 30,
 'mt. laurel': 11,
 'skippack': 27,
 'st. albert': 33,
 'richboro': 35,
 'hockessin': 37,
 'kulpsville': 8,
 'wood river': 29,
 'beech grove': 16,
 'hamilton township': 10,
 'westville': 13,
 'plymouth meeting': 35,
 'dresher': 21,
 'berlin': 36,
 'paulsboro': 17,
 'clayton': 109,
 'millstadt': 13,
 'holland': 10,
 'sahuarita': 17,
 'trinity': 27,
 'valley park': 31,
 'montecito': 27,
 'overland': 17,
 'yeadon': 6,
 'saint ann': 27,
 'feasterville': 20,
 'dupo': 2,
 'garden city': 38,
 'plumsteadville': 4,
 'temple terrace': 59,
 'deptford': 40,
 'flanders': 1,
 'nashville-davidson metropolitan government (balance)': 2,
 "o'fallon": 61,
 'nolensville': 37,
 'boyertown': 24,
 'perkiomenville': 4,
 'safety harbor': 54,
 'vineland': 1,
 'lafayette hill': 25,
 'caseyville': 14,
 'thonotosassa': 6,
 'lester': 3,
 'vail': 17,
 'florence': 5,
 'hillsborough county': 2,
 'mansfield': 1,
 'south cinnaminson': 1,
 'mt laurel': 3,
 'elkins park': 43,
 'webster groves': 43,
 'oro valley': 80,
 'feasterville-trevose': 27,
 'imperial': 17,
 'maple glen': 15,
 'north redington beach': 13,
 'glendora': 12,
 'belmont hills': 1,
 'oaklyn': 18,
 'southport': 4,
 'st.rose': 1,
 'runnemede': 23,
 'pleasant view': 23,
 'shrewsbury': 3,
 'newfield': 4,
 'hainesport': 15,
 'wyncote': 26,
 'somerdale': 22,
 'berwyn': 46,
 'south pasadena': 17,
 'chester springs': 26,
 'perkasie': 37,
 'folcroft': 16,
 'gloucester city': 20,
 'west conshohocken': 6,
 'tuscon': 5,
 'berlin township': 3,
 'monroe township': 5,
 'pennsburg': 12,
 'indian rocks beach': 38,
 'pennsauken': 57,
 'sellersville': 14,
 'hatfield': 35,
 'boone': 2,
 'west deptford': 19,
 'mercerville': 1,
 'rockledge': 5,
 'linwood': 5,
 'stratford': 19,
 'belle chase': 1,
 'twin oaks': 2,
 'marrero': 77,
 'new britain': 5,
 'frazer': 19,
 'nw edmonton': 1,
 'maple shade township': 9,
 'villanova': 12,
 'sun city': 1,
 'radnor': 14,
 'trevose': 18,
 'avondale': 20,
 'croydon': 20,
 'lindenwold': 25,
 'warson woods': 2,
 'oreland': 10,
 'salem': 10,
 'swarthmore': 16,
 'thorndale': 17,
 'st. charles': 46,
 'buckingham': 12,
 'pittsgrove township': 1,
 'logan township': 6,
 'talleyville': 3,
 'wynnewood': 28,
 'tabernacle': 8,
 'cinnaminson': 44,
 'lawrence': 16,
 'westtown': 2,
 'clifton heights': 34,
 'st louis downtown': 7,
 'mount holly': 48,
 'lemay': 1,
 'phila': 3,
 'souderton': 39,
 'boothwyn': 19,
 'westchase': 4,
 'westampton township': 1,
 'westampton': 12,
 'saint albert': 11,
 'flourtown': 21,
 'telford': 17,
 'frontenac': 11,
 'colmar': 12,
 'lula lula': 1,
 'sunset hills': 11,
 'jeffersonville': 4,
 'edgewater park': 4,
 'columbus': 14,
 'holland southampton': 1,
 'pike creek': 2,
 'pontoon beach': 5,
 'delanco': 3,
 'collingdale': 15,
 'feasterville trevose': 23,
 'bywater': 1,
 'thorofare': 7,
 'new palestine': 8,
 'haddon township': 28,
 'carrollwood': 3,
 'trainer': 1,
 'furlong': 2,
 'belleair bluffs': 14,
 'twn n cntry': 1,
 'hamilton': 22,
 'east alton': 11,
 'concordville': 4,
 'red hill': 3,
 'lithia': 31,
 'national park': 4,
 'unionville': 2,
 'sharon hill': 8,
 'clarksboro': 3,
 'tinicum': 1,
 'southeast edmonton': 1,
 'oakville': 5,
 'wyndmoor': 9,
 'st ann': 3,
 'gibsonton': 16,
 'upper pittsgrove': 1,
 'devon': 11,
 'kenneth city': 20,
 'westmont': 16,
 'harrison township': 6,
 'abington township': 1,
 'marcus hook': 12,
 'w.chester': 1,
 'pinecrest west park': 1,
 'w cherry hill': 1,
 'aldan': 6,
 'deptford township': 12,
 'lawnside': 8,
 'pemberton': 6,
 'pipersville': 13,
 'elmer': 9,
 'tierra verde': 14,
 'franklinville': 8,
 'clermont': 4,
 'laurel springs': 8,
 'haverford': 6,
 'pennsauken township': 17,
 'birchrunville': 2,
 'rock hill': 6,
 'joelton': 11,
 'mount lemmon': 4,
 'breckenridge hills': 3,
 'boise city': 7,
 'lawrence township': 6,
 'ozona': 3,
 'evesham township': 15,
 'pittsgrove': 2,
 'mccordsville': 12,
 'west edmonton': 2,
 'whitestown': 23,
 'saintt petersburg': 1,
 'bellville': 1,
 'rosewood heights': 1,
 'ladue': 5,
 'east nashville': 2,
 'roslyn': 8,
 'garnet valley': 13,
 'marlborough': 2,
 'worcester': 4,
 'upper chichester': 5,
 'berry hill': 3,
 'primos': 6,
 'ashland': 1,
 'bethalto': 6,
 'river ridge': 13,
 'valencia west': 1,
 'mantua': 11,
 'holicong': 2,
 'newport': 3,
 'pine hill': 13,
 'coatesville': 9,
 'fairview hts.': 2,
 'gwynedd valley': 1,
 'bryn athyn': 1,
 'palmetto': 6,
 'violet': 4,
 'crum lynne': 2,
 'upper gwynedd': 1,
 'west deptford townsh': 1,
 'inglewood': 1,
 'malaga': 8,
 'southwest tampa': 1,
 'jamison': 13,
 'cedar brook': 3,
 'titusville': 2,
 'ivyland': 6,
 'christiana': 6,
 'melrose park': 2,
 'richmond heights': 29,
 'magnolia': 12,
 'carneys point': 5,
 'sun valley': 12,
 'hulmeville': 4,
 'beverly': 8,
 'southampton township': 3,
 'sappington': 7,
 'town n country': 1,
 'wyndlake condominium': 1,
 'holmes': 16,
 "land o'lakes": 2,
 'norwood': 7,
 'merion station': 9,
 'green lane': 5,
 'east saint louis': 7,
 'mantua township': 2,
 'burlington township': 3,
 'lower providence': 1,
 'mc cordsville': 1,
 'silverdale': 2,
 'catalina': 7,
 'woodson terrace': 1,
 'st pete': 1,
 'bargersville': 3,
 'mt laurel twp, nj': 1,
 'gibbstown': 10,
 'gladwyne': 3,
 'tren': 1,
 'skippack village': 3,
 'west mount holly': 1,
 'gloucester township': 8,
 'indian shores': 10,
 'penndel': 11,
 'camby': 19,
 'pennsville township': 3,
 'eastampton': 3,
 'hilltop': 1,
 'erdenheim': 3,
 'thonosassa': 1,
 'elk township': 1,
 'summerland': 9,
 'berkeley': 7,
 'cheltenham': 8,
 'danville': 4,
 'chesterbrook': 4,
 'balm': 1,
 'bethel': 1,
 'eaux claires': 1,
 'evesham': 5,
 'east st. louis': 2,
 'glenoldan': 1,
 'zieglerville': 2,
 'meraux': 5,
 'haddon twp': 1,
 'mont clare': 2,
 'winslow township': 4,
 'concord township': 1,
 'blvd': 1,
 'luling': 4,
 'bucks': 2,
 'westmont - haddon towsship': 1,
 'wilmington manor': 2,
 'east lansdowne': 1,
 'scott air force base': 5,
 'san antonio': 8,
 'cheltenham township': 2,
 'franconia': 1,
 'smithton': 5,
 'lionville': 2,
 'wrightstown': 3,
 'carversville': 2,
 'crestwood': 7,
 'green park': 3,
 'cornwells heights': 1,
 'saint rose': 5,
 'olivette': 10,
 'indianopolis': 1,
 'st.petersburg': 7,
 'st.louis': 7,
 'belleair blf': 2,
 'bristol twp': 1,
 'kenneth': 1,
 'trolley square': 1,
 'kalispell': 1,
 'manayunk': 6,
 'glendale': 1,
 'pineville': 1,
 'st. rose': 2,
 'kingston springs': 9,
 'milmont park': 1,
 'southwest philadelphia': 3,
 'greenfield': 5,
 'bethel township': 1,
 'saint bernard': 2,
 'vincentown': 3,
 'belle meade': 2,
 'west point': 3,
 'elsmere': 2,
 'washington twp': 1,
 'castleton': 4,
 'hammonton': 10,
 'riveridge': 1,
 'bridge city': 2,
 'chesilhurst': 3,
 'redington shores': 12,
 'rural hill': 1,
 'washington township': 4,
 'fairview hts': 1,
 'st. ann': 4,
 'philadephia': 1,
 'wenonah': 7,
 'quinton': 1,
 'eastampton township': 2,
 'woolwich twp.': 1,
 'new whiteland': 4,
 'downtown': 2,
 'oldmans township': 1,
 'wanamaker': 1,
 'mt. holly': 1,
 'kimmswick': 5,
 'saint peters': 3,
 'greater northdale': 1,
 'bayonet point': 2,
 'toughkenamon': 5,
 'freehold': 1,
 'gentilly': 1,
 'masaryktown': 1,
 "town 'n' country": 4,
 'hamiltion': 1,
 'lutz fl': 1,
 'gwynedd': 2,
 'fortville': 1,
 'fairview': 2,
 'gardenville': 1,
 'pleasant township': 1,
 'thornton': 2,
 'gulph mills': 1,
 'springhill': 1,
 'mehlville': 1,
 'redingtn shor': 2,
 'hancock': 1,
 'north redington bch': 1,
 'pilesgrove': 6,
 'mt.laurel': 3,
 'dade city': 3,
 'mt.juliet': 1,
 'wallingford': 1,
 'sassamansville': 1,
 'line lexington': 3,
 'fox street': 1,
 'fairview village': 2,
 'conshohoeken': 1,
 'medford lakes': 4,
 'cumberland': 2,
 'south tucson': 2,
 'linfield': 2,
 'jobstown': 1,
 'peerless park': 1,
 'saint petersburg beach': 1,
 'erial': 1,
 'drexel heights': 1,
 'eddington': 1,
 'fairmont city': 2,
 'e. norristown': 1,
 'mount royal': 1,
 'black jack': 1,
 'picture rocks': 1,
 'marshallton': 1,
 'solebury': 1,
 'waterford works': 2,
 'center square': 1,
 "o' fallon": 1,
 'bucktown': 1,
 'west chester pa': 1,
 'chalemette': 1,
 'lima': 1,
 'mango': 1,
 'east edmonton': 1,
 'tylersport': 1,
 'scott afb': 2,
 'delran twp': 1,
 'west trenton': 2,
 'algiers': 1,
 'martinsville': 2,
 'st. davids': 1,
 'largo (walsingham)': 1,
 'upper southampton': 1,
 'sumneytown': 3,
 'pennsylvania': 2,
 'st. peters': 2,
 'cedars': 4,
 'moorestown-lenola': 1,
 "carney's point": 1,
 'woolwich township': 2,
 'enoch': 1,
 'citrus park': 2,
 'edgemont': 1,
 'lower merion': 1,
 'town & country': 1,
 'whites creek': 3,
 'warrington township': 2,
 'cottage hills': 2,
 'pennington': 1,
 'east st louis': 2,
 'metarie': 1,
 'stowe': 4,
 'west bradford township': 1,
 'pinellas': 2,
 'lawrenceville': 2,
 'stead': 1,
 'hi-nella': 2,
 'roebling': 4,
 'south tampa': 1,
 'parkside': 1,
 'saint john': 1,
 'fieldsboro': 1,
 'festerville': 1,
 'liverpool': 1,
 'donelson': 1,
 'goodletsville': 1,
 'sauget': 1,
 'casas adobes': 1,
 'nampa': 1,
 'north coventry township': 1,
 'sherwood': 1,
 'lederach': 3,
 'corona de tucson': 2,
 'washington park': 1,
 'bensalem township': 1,
 'pine forge': 1,
 'newportville': 1,
 'lower southampton township': 1,
 'n redngtn bch': 1,
 'east falls': 1,
 'ridley': 1,
 'bensalem. pa': 1,
 'riverview fl': 1,
 'newtown sqaure': 1,
 'bellefontaine': 1,
 'westhampton': 1,
 'chichester': 2,
 'bellefontaine neighbors': 1,
 'upper pottsgrove': 1,
 'w. berlin': 1,
 'kuna': 3,
 'winchester': 2,
 'dellwood': 1,
 'montchanin': 2,
 'saint louis,': 1,
 'indiana': 1,
 'st petersurg': 1,
 'elmwood': 2,
 'upland': 1,
 'gloucester': 1,
 'monroeville': 1,
 'plainfiled': 1,
 'st.charles': 1,
 'philly': 1,
 'alloway': 2,
 'tierre verde': 1,
 'stanton': 1,
 'sanatoga': 1,
 'foster pond': 1,
 'wycombe': 1,
 'santa  barbara': 1,
 'swedeland': 1,
 'truckee': 1,
 'west collingswood heights': 1,
 'tampa,fl': 1,
 'tampa palms': 1,
 'n.wales': 1,
 'montgomery': 1,
 'sullivan': 1,
 'blooming glen': 1,
 'st louis county': 1,
 'bel ridge': 1,
 'hilltown': 1,
 'london grove': 1,
 'inpolis': 1,
 'clarksville': 1,
 'delran township': 1,
 'cane ridge': 1,
 'st. leo': 1,
 'hurffville': 1,
 'kirklyn': 1,
 'redington shore': 1,
 'clearwater/ countryside': 1,
 'caln': 1,
 'st. louis county': 1,
 'pass-a-grille beach': 1,
 'hollywood': 1,
 'hernando bch': 1,
 'cold springs': 1,
 'middletown': 1,
 'saint leo': 1,
 'mt holly': 1,
 'newton': 1,
 's.pasadena': 1,
 'churchville': 1,
 'st.  charles': 1,
 'charlotte': 1,
 'woodbury hts.': 1,
 'mount holly,': 1,
 'tampa florida': 1,
 'upper moreland': 1}

,review_id,user_id,business_id,stars,text
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,"If you decide to eat here, just be aware it is..."
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,I've taken a lot of spin classes over the year...
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,Family diner. Had the buffet. Eclectic assortm...
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,"Wow! Yummy, different, delicious. Our favo..."
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,Cute interior and owner (?) gave us tour of up...